auth:
  type: DISABLED
kafka:
  clusters:
    - name: kafka-cluster-1
      bootstrapServers: kafka:29092
      readOnly: false
      serde: []
      properties: {}
      consumerProperties: {}
      producerProperties: {}
      schemaRegistryTopicSubjectSuffix: -value
      kafkaConnect: []
      masking: []
rbac:
  roles: []
webclient: {}
